### ISSUE TITLE
Issues with "File" configuration

### ISSUE THREAD

**Issue by oups13** [endemecio02/node-red-contrib-httpauth#5]
Hi,

I would like to use the "File" configuration because I need to configure multiple users.
However, the only user that I can authenticate with is always the last one defined in the file.

For exemple, if the contents of my file is:
user1:myrealm:pass1
user2:myrealm:pass2
user3:myrealm:pass3

The only user I'm able to authenticate with is user3 (the last user defined in the file).
What am I doing wrong?

Thank you for your help.

**Comment by michaelblight** [comment]
Is this an issue with using a file that has CR/LF endings rather than Unix-style LF? See [here](https://stackoverflow.com/questions/54794427/nodered-httpauth-node-file-type-credential/54799136#54799136).

**Comment by oups13** [comment]
That's it! Thanks alot for helping me resolve this issue.
